import type { Category, Product } from '@/lib/types';
import {
  Shirt,
  User,
  Smartphone,
  Home,
  Bike,
  ToyBrick,
  Watch,
  Headphones,
  Laptop,
  Lamp,
  Book,
  Camera,
  Paintbrush,
  Utensils,
  Sofa,
} from 'lucide-react';

export const categories: Category[] = [
  { name: "Women's Fashion", icon: Shirt },
  { name: "Men's Fashion", icon: User },
  { name: 'Electronics', icon: Smartphone },
  { name: 'Home & Garden', icon: Home },
  { name: 'Sports & Outdoors', icon: Bike },
  { name: 'Toys & Hobbies', icon: ToyBrick },
  { name: 'Watches & Jewelry', icon: Watch },
  { name: 'Health & Beauty', icon: Paintbrush },
  { name: 'Automotive', icon: Utensils },
];

function getImageUrl(id: string): string {
    // This is a dummy function, as we are now using direct URLs.
    // Kept for initial data generation.
    return `https://picsum.photos/seed/${id}/600/400`;
}

const allProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Smartwatch with Heart Rate Monitor',
    description: 'Stay connected and track your fitness with this stylish smartwatch. Features a vibrant AMOLED display, long battery life, and comprehensive health monitoring.',
    price: 129.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviews: 2450,
    sold: 5200,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1668760180303-fcfe2b899e20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxzbWFydHdhdGNoJTIwdGVjaG5vbG9neXxlbnwwfHx8fDE3NjM5NjEzMDN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Tech Wonders' },
    published: true,
  },
  {
    id: '2',
    name: 'Noise-Cancelling Wireless Over-Ear Headphones',
    description: 'Immerse yourself in pure sound with these premium noise-cancelling headphones. Enjoy crystal-clear audio, plush comfort, and up to 30 hours of playtime.',
    price: 89.5,
    rating: 4.6,
    reviews: 1890,
    sold: 4300,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1657223144998-e5aa4fa2db7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx3aXJlbGVzcyUyMGhlYWRwaG9uZXN8ZW58MHx8fHwxNzY0MDIwMDk0fDA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'SoundScape' },
    published: true,
  },
  {
    id: '3',
    name: 'Lightweight Laptop Backpack with USB Port',
    description: 'The perfect companion for your daily commute or travel. This backpack features a dedicated laptop compartment, multiple pockets, and a built-in USB charging port.',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.9,
    reviews: 3120,
    sold: 7800,
    category: "Men's Fashion",
    imageUrl: 'https://images.unsplash.com/photo-1673505705697-763b670e9afd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxsYXB0b3AlMjBiYWNrcGFja3xlbnwwfHx8fDE3NjQwNjY0MjN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Urban Gear' },
    published: true,
  },
  {
    id: '4',
    name: 'Adjustable LED Desk Lamp with Wireless Charging',
    description: 'Illuminate your workspace with this modern LED desk lamp. It offers multiple brightness levels, color temperatures, and a convenient wireless charging base for your phone.',
    price: 45.0,
    rating: 4.7,
    reviews: 980,
    sold: 2100,
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1551380701-5dd33d5b5d06?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxkZXNrJTIwbGFtcHxlbnwwfHx8fDE3NjM5OTQ2NTJ8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Bright Ideas' },
    published: true,
  },
  {
    id: '5',
    name: 'Breathable Mesh Running Shoes for Men',
    description: 'Achieve your personal best with these lightweight and breathable running shoes. The mesh upper provides excellent ventilation, while the cushioned sole offers superior comfort.',
    price: 64.95,
    rating: 4.5,
    reviews: 1250,
    sold: 3500,
    category: 'Sports & Outdoors',
    imageUrl: 'https://images.unsplash.com/photo-1469395446868-fb6a048d5ca3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxydW5uaW5nJTIwc2hvZXN8ZW58MHx8fHwxNzY0MDQ0MDAyfDA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'QuickStride' },
    published: true,
  },
  {
    id: '6',
    name: 'Eco-Friendly Non-Slip Yoga Mat',
    description: 'Find your balance on this eco-friendly yoga mat. Made from sustainable materials, it provides a non-slip surface for a safe and comfortable practice.',
    price: 29.99,
    originalPrice: 40.0,
    rating: 4.8,
    reviews: 860,
    sold: 1800,
    category: 'Sports & Outdoors',
    imageUrl: 'https://images.unsplash.com/photo-1591291621164-2c6367723315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx5b2dhJTIwbWF0fGVufDB8fHx8MTc2Mzk3MzUzNnww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'ZenFlow' },
    published: true,
  },
  {
    id: '7',
    name: 'Vintage Leather Journal Notebook',
    description: 'Capture your thoughts and ideas in this beautifully crafted leather journal. It features high-quality paper and a timeless design.',
    price: 24.5,
    rating: 4.9,
    reviews: 1500,
    sold: 4000,
    category: 'Toys & Hobbies',
    imageUrl: 'https://images.unsplash.com/photo-1677064061401-f77f966ff8a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxsZWF0aGVyJTIwam91cm5hbHxlbnwwfHx8fDE3NjQwMTE1MDJ8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Paper Drams' },
    published: true,
  },
  {
    id: '8',
    name: 'Compact 4K Digital Camera with Flip Screen',
    description: 'Perfect for vlogging and content creation, this compact 4K camera features a flip screen, excellent image quality, and easy-to-use controls.',
    price: 499.0,
    originalPrice: 650.0,
    rating: 4.6,
    reviews: 650,
    sold: 1200,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1616423640778-28d1b53229bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxkaWdpdGFsJTIwY2FtZXJhfGVufDB8fHx8MTc2Mzk3OTc2Nnww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Pixel Perfect' },
    published: true,
  },
  {
    id: '9',
    name: 'Stainless Steel French Press Coffee Maker',
    description: 'Brew rich, flavorful coffee at home with this durable stainless steel French press. Its double-wall insulation keeps your coffee hot longer.',
    price: 34.99,
    rating: 4.7,
    reviews: 1100,
    sold: 3200,
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1609296583302-f53723390e83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxjb2ZmZWUlMjBwcmVzc3xlbnwwfHx8fDE3NjQwNjY0MjN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Brew Masters' },
    published: true,
  },
  {
    id: '10',
    name: 'Minimalist Slim Wallet with RFID Blocking',
    description: 'Carry your essentials in style with this slim and secure wallet. It features RFID-blocking technology to protect your cards and a minimalist design for a modern look.',
    price: 19.95,
    rating: 4.8,
    reviews: 2800,
    sold: 6500,
    category: "Men's Fashion",
    imageUrl: 'https://images.unsplash.com/photo-1637168943285-a8f9ea0dc3f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxsZWF0aGVyJTIwd2FsbGV0fGVufDB8fHx8MTc2Mzk2NTQyMHww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'SecurePockets' },
    published: true,
  },
  {
    id: '11',
    name: 'Organic Beard Oil and Balm Grooming Kit',
    description: 'Tame and nourish your beard with this all-natural grooming kit. Includes beard oil and balm made with organic ingredients to soften and style your facial hair.',
    price: 28.5,
    originalPrice: 35.0,
    rating: 4.9,
    reviews: 950,
    sold: 2100,
    category: 'Health & Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1620018646973-e3e257a1002c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxiZWFyZCUyMG9pbHxlbnwwfHx8fDE3NjQwNjY0MjN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Grooming Co.' },
    published: true,
  },
  {
    id: '12',
    name: "Women's Floral Print Summer Maxi Dress",
    description: 'Embrace the summer vibe with this elegant floral maxi dress. Made from lightweight fabric, it\'s perfect for casual outings or beach days.',
    price: 42.0,
    rating: 4.5,
    reviews: 750,
    sold: 1800,
    category: "Women's Fashion",
    imageUrl: 'https://images.unsplash.com/photo-1496217590455-aa63a8350eea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8c3VtbWVyJTIwZHJlc3N8ZW58MHx8fHwxNzY0MDYzNjA1fDA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Summer Blooms' },
    published: true,
  },
  {
    id: '13',
    name: 'Portable Bluetooth Speaker with 24-Hour Battery',
    description: 'Take your music anywhere with this powerful and portable Bluetooth speaker. It offers rich sound, a rugged waterproof design, and an impressive 24-hour battery life.',
    price: 55.99,
    rating: 4.7,
    reviews: 1950,
    sold: 4500,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1507878566509-a0dbe19677a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Ymx1ZXRvb3RoJTIwc3BlYWtlcnxlbnwwfHx8fDE3NjQwNjQwOTR8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'SoundWave' },
    published: true,
  },
  {
    id: '14',
    name: '1000-Piece Jigsaw Puzzle - "Starry Night"',
    description: 'Challenge yourself with this stunning 1000-piece jigsaw puzzle featuring Van Gogh\'s masterpiece, "Starry Night." A rewarding experience for puzzle enthusiasts.',
    price: 18.99,
    rating: 4.9,
    reviews: 1200,
    sold: 3500,
    category: 'Toys & Hobbies',
    imageUrl: 'https://images.unsplash.com/photo-1591040092219-081fb773589c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8amlnc2F3JTIwcHV6emxlfGVufDB8fHx8MTc2NDA0MDIyOHww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Puzzle Place' },
    published: true,
  },
  {
    id: '15',
    name: 'Professional 15-Piece Kitchen Knife Set',
    description: 'Upgrade your culinary skills with this professional-grade knife set. Includes all the essential knives for any kitchen task, crafted from high-carbon stainless steel.',
    price: 139.95,
    originalPrice: 199.95,
    rating: 4.8,
    reviews: 1600,
    sold: 3900,
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1760594308330-404765c714b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxrbmlmZSUyMHNldHxlbnwwfHx8fDE3NjQwMDI2NzN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Culinary Edge' },
    published: true,
  },
  {
    id: '16',
    name: 'Smart WiFi Power Strip with 4 Outlets',
    description: 'Control your devices from anywhere with this smart power strip. Features 4 individually controlled outlets, USB ports, and compatibility with voice assistants.',
    price: 25.99,
    rating: 4.6,
    reviews: 900,
    sold: 2800,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1583288264462-01f05e6b5548?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxwb3dlciUyMHN0cmlwfGVufDB8fHx8MTc2NDA2NjQyM3ww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'ConnectLife' },
    published: true,
  },
  {
    id: '17',
    name: "Men's Classic Denim Jacket",
    description: 'A timeless wardrobe staple. This classic denim jacket is made from durable, high-quality denim and features a comfortable fit for everyday wear.',
    price: 75.0,
    rating: 4.7,
    reviews: 1150,
    sold: 3200,
    category: "Men's Fashion",
    imageUrl: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxkZW5pbSUyMGphY2tldHxlbnwwfHx8fDE3NjM5OTUzNDN8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Rugged Wear' },
    published: true,
  },
  {
    id: '18',
    name: 'Set of 3 Succulent Plants in Ceramic Pots',
    description: 'Add a touch of green to your space with this set of three easy-care succulent plants. They come in stylish ceramic pots, perfect for any home or office.',
    price: 22.5,
    rating: 4.8,
    reviews: 850,
    sold: 2500,
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1620444616342-d27488af69b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8c3VjY3VsZW50JTIwcGxhbnRzfGVufDB8fHx8MTc2Mzk4MzU4Nnww&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Green Thumbs' },
    published: true,
  },
  {
    id: '19',
    name: 'Insulated Stainless Steel Water Bottle',
    description: 'Keep your drinks cold for 24 hours or hot for 12 with this insulated water bottle. It\'s leak-proof, durable, and perfect for an active lifestyle.',
    price: 21.99,
    rating: 4.9,
    reviews: 2300,
    sold: 5500,
    category: 'Sports & Outdoors',
    imageUrl: 'https://images.unsplash.com/photo-1616118133712-8c947f7b822c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx3YXRlciUyMGJvdHRsZXxlbnwwfHx8fDE3NjM5NjU2ODF8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'HydratePro' },
    published: true,
  },
  {
    id: '20',
    name: 'Electric Gooseneck Kettle for Coffee & Tea',
    description: 'Achieve the perfect pour-over with this precision gooseneck kettle. It features variable temperature control and a sleek design for your modern kitchen.',
    price: 59.95,
    originalPrice: 79.95,
    rating: 4.8,
    reviews: 1400,
    sold: 3600,
    category: 'Home & Garden',
    imageUrl: 'https://images.unsplash.com/photo-1738520420652-0c47cea3922b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxlbGVjdHJpYyUyMGtldHRsZXxlbnwwfHx8fDE3NjQwMjE1MTJ8MA&ixlib-rb-4.1.0&q=80&w=1080',
    store: { name: 'Perfect Pour' },
    published: true,
  },
];

export let products: Product[] = [...allProducts];
export const superDeals: Product[] = allProducts.filter(p => p.originalPrice).slice(0, 5);
